CREATE DATABASE Tienda_Zapatos;
GO
USE Tienda_Zapatos;
GO

CREATE TABLE Zapatos (
	id INT PRIMARY KEY IDENTITY(1,1),
	nombre NVARCHAR(100) NOT NULL,
	marca NVARCHAR(50) NOT NULL,
	talla NVARCHAR(10) NOT NULL,
	precio DECIMAL(10, 2) NOT NULL,
	descripcion NVARCHAR(255) NULL
);

CREATE TABLE Clientes (
	id INT PRIMARY KEY IDENTITY(1,1),
	nombre NVARCHAR(100) NOT NULL,
	email NVARCHAR(100) NOT NULL UNIQUE,
	telefono NVARCHAR(15) NOT NULL
);

CREATE TABLE Empleados (
	id INT PRIMARY KEY IDENTITY(1,1),
	nombre NVARCHAR(100) NOT NULL,
	cedula NVARCHAR(100) NOT NULL UNIQUE,
	salario NVARCHAR(15) NOT NULL,
	telefono NVARCHAR(15) NOT NULL
);

CREATE TABLE Inventario (
	id INT PRIMARY KEY IDENTITY(1,1),
	codigo NVARCHAR(50) NOT NULL UNIQUE,
	zapato INT NOT NULL,
	cantidad INT NOT NULL,
	FOREIGN KEY (zapato) REFERENCES Zapatos(id)
);

CREATE TABLE Compras (
	id INT PRIMARY KEY IDENTITY(1,1),
	fecha DATETIME NOT NULL DEFAULT GETDATE(),
	metodoPago NVARCHAR(50) NOT NULL,
	total DECIMAL(10, 2) NOT NULL,
	codigo NVARCHAR(50) NOT NULL UNIQUE,

	cliente INT NOT NULL,
	empleado INT NOT NULL,
	FOREIGN KEY (cliente) REFERENCES Clientes(id),
	FOREIGN KEY (empleado) REFERENCES Empleados(id)
);
